///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CoverModel {

  int? id;
  bool? alphaChannel;
  bool? animated;
  int? game;
  int? height;
  String? imageId;
  String? url;
  int? width;
  String? checksum;

  CoverModel({
    this.id,
    this.alphaChannel,
    this.animated,
    this.game,
    this.height,
    this.imageId,
    this.url,
    this.width,
    this.checksum,
  });
  CoverModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    alphaChannel = json['alpha_channel'];
    animated = json['animated'];
    game = json['game']?.toInt();
    height = json['height']?.toInt();
    imageId = json['image_id']?.toString();
    url = json['url']?.toString();
    width = json['width']?.toInt();
    checksum = json['checksum']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['alpha_channel'] = alphaChannel;
    data['animated'] = animated;
    data['game'] = game;
    data['height'] = height;
    data['image_id'] = imageId;
    data['url'] = url;
    data['width'] = width;
    data['checksum'] = checksum;
    return data;
  }
}
